name: "gradle-wrapper-verification"
on: [push, pull_request]

jobs:
    verify:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: eskatos/gradle-wrapper-check@releases/v1
